"""SDL Generator — convert aligned draft ontology to SDL YAML starter template.

OntoRAG step 3 of 3.

Generates an SDL YAML file that:
1. Defines entity types mapped to their aligned OWL classes
2. Infers candidate metric definitions from numeric properties
3. Writes the output to pilot/fibo-banking/generated_sdl.yaml
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
import yaml
from loguru import logger

from .ontology_extractor import DraftOntology
from .skos_aligner import AlignmentMap

# Output path relative to repo root
_DEFAULT_OUTPUT_PATH = Path(__file__).parents[7] / "pilot" / "fibo-banking" / "generated_sdl.yaml"

# Numeric datatype hints that indicate a property can be a metric
_NUMERIC_HINTS = {"integer", "decimal", "float", "number", "amount", "count", "sum", "total",
                  "percentage", "ratio", "rate", "score", "quantity", "volume", "balance"}


def _is_numeric_property(name: str, dtype: str) -> bool:
    combined = f"{name} {dtype}".lower()
    return any(hint in combined for hint in _NUMERIC_HINTS)


def _camel_to_snake(name: str) -> str:
    import re
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


class SDLGenerator:
    """Convert aligned ontology to SDL YAML starter template.

    SDL schema format (subset relevant for generation):
    ```yaml
    version: "1.0"
    entities:
      - name: LegalEntity
        ontology_class: "https://spec.edmcouncil.org/fibo/..."
        description: "..."
        fields:
          - name: name
            type: string
          - name: registration_number
            type: string
    metrics:
      - name: total_transaction_amount
        description: "Sum of transaction amounts"
        entity: Transaction
        field: amount
        aggregation: SUM
    ```
    """

    def __init__(self, output_path: str | Path | None = None) -> None:
        self._output_path = Path(output_path or _DEFAULT_OUTPUT_PATH)

    def generate(
        self,
        draft_ontology: DraftOntology,
        alignment_map: AlignmentMap,
        tenant_id: str = "default",
        ontology_module: str = "fibo",
    ) -> dict[str, Any]:
        """Generate SDL YAML from draft ontology + alignment.

        Args:
            draft_ontology: Output of OntologyExtractor.
            alignment_map: Output of SKOSAligner.
            tenant_id: SDL tenant context.
            ontology_module: Primary ontology module name.

        Returns:
            SDL dict (also written to output_path).
        """
        entities = []
        metrics = []

        for cls in draft_ontology.classes:
            alignment = alignment_map.get(cls.name)

            entity: dict[str, Any] = {
                "name": cls.name,
                "description": cls.description,
            }

            if alignment and alignment.matched_class:
                entity["ontology_class"] = alignment.matched_class
                entity["skos_match_type"] = alignment.skos_match_type
                entity["alignment_confidence"] = round(alignment.confidence, 3)
            else:
                entity["ontology_class"] = f"https://usf.io/ontology/{cls.name}"
                entity["alignment_confidence"] = 0.0
                entity["note"] = "No industry standard match found — review manually"

            # Fields from properties
            fields = []
            for prop_name, dtype in cls.properties.items():
                field_def: dict[str, Any] = {
                    "name": _camel_to_snake(prop_name),
                    "type": self._map_dtype(dtype),
                    "source_property": prop_name,
                }
                fields.append(field_def)

                # Candidate metric from numeric property
                if _is_numeric_property(prop_name, dtype):
                    metric_name = f"total_{_camel_to_snake(cls.name)}_{_camel_to_snake(prop_name)}"
                    metrics.append({
                        "name": metric_name,
                        "description": f"Sum of {prop_name} across all {cls.name} instances",
                        "entity": cls.name,
                        "field": _camel_to_snake(prop_name),
                        "aggregation": "SUM",
                        "filter": None,
                        "note": "Generated by OntoRAG — verify business definition",
                    })

            entity["fields"] = fields
            entities.append(entity)

        # Relationships as SDL join definitions
        joins = []
        for rel in draft_ontology.relationships:
            joins.append({
                "name": rel.name,
                "from": rel.from_class,
                "to": rel.to_class,
                "cardinality": rel.cardinality,
                "description": rel.description,
            })

        sdl = {
            "version": "1.0",
            "meta": {
                "generated_by": "OntoRAG/SDLGenerator",
                "ontology_module": ontology_module,
                "tenant_id": tenant_id,
                "source_documents": draft_ontology.source_documents,
                "domain_hint": draft_ontology.domain_hint,
                "note": "DRAFT — review ontology_class alignments before publishing",
            },
            "entities": entities,
            "metrics": metrics,
            "joins": joins,
        }

        self._write(sdl)
        logger.info(
            "SDL generated",
            entities=len(entities),
            metrics=len(metrics),
            joins=len(joins),
            output=str(self._output_path),
        )
        return sdl

    def _write(self, sdl: dict[str, Any]) -> None:
        self._output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self._output_path, "w") as f:
            yaml.dump(sdl, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def _map_dtype(self, dtype_hint: str) -> str:
        dtype_lower = dtype_hint.lower()
        if any(t in dtype_lower for t in ["int", "count", "number"]):
            return "integer"
        if any(t in dtype_lower for t in ["decimal", "float", "amount", "balance", "ratio", "rate"]):
            return "decimal"
        if "bool" in dtype_lower:
            return "boolean"
        if "date" in dtype_lower:
            return "date"
        return "string"
