import {
  Component, ChangeDetectionStrategy, inject, signal
} from '@angular/core';
import { MockService } from '../../core/api/mock.service';
import { AuditEntry } from '../../core/models';
import { UpperCasePipe } from '@angular/common';
import { ProvOPanelComponent } from '../../shared/components/prov-o-panel/prov-o-panel.component';
import { RelativeTimePipe } from '../../shared/pipes/relative-time.pipe';

@Component({
  selector: 'usf-audit-log',
  standalone: true,
  imports: [ProvOPanelComponent, RelativeTimePipe, UpperCasePipe],
  templateUrl: './log.component.html',
  styleUrl: './log.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AuditLogComponent {
  private mock = inject(MockService);

  entries = signal(this.mock.auditEntries);
  expandedId = signal<string | null>(null);

  toggleExpand(id: string): void {
    this.expandedId.set(this.expandedId() === id ? null : id);
  }

  decisionClass(decision: string): string {
    return decision === 'allow' ? 'badge-success' : 'badge-error';
  }

  exportRdf(): void {
    // Mock export
    const blob = new Blob(['# PROV-O RDF Export\n# Generated by USF Audit\n'], { type: 'text/turtle' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'usf-audit-export.ttl';
    a.click();
    URL.revokeObjectURL(url);
  }
}
